### ISSUE TITLE
复制源码请保留开源协议文件

### ISSUE THREAD

**Issue by kahaani** [laubonghaudoi/Chinese_Rime#1]
[Kahaani/dieghv](https://github.com/Kahaani/dieghv) 是以 GPL-3.0 开源的，依照 GPL 的要求，复制源码到本项目时应该保留 LICENSE 文件：
https://github.com/Kahaani/dieghv/blob/master/LICENSE

其实，对于收藏类项目，推荐用 [git submodule](https://git-scm.com/docs/git-submodule) 来做，这样方便更新子项目的后续改动。

**Comment by laubonghaudoi** [comment]
抱歉，第一次做收藏类项目没有相关经验，是否把LICENCE文件添加至`/data/潮语`下即可？

**Comment by kahaani** [comment]
> 是否把LICENCE文件添加至`/data/潮语`下即可

可以。其他目录下的码表和 [Kahaani/dieghv](https://github.com/Kahaani/dieghv) 无关，是独立的，所以这样做应该就可以了。谢谢。

**Comment by laubonghaudoi** [comment]
关于使用submodule来做收藏类项目，我考察了一下，暂时有一个疑问，就是很多方案的作者并无编程经验且不会使用github，这样无法使每个输入方案都用submodule来保持独立更新，所以是否保持现在的形式，通过联系作者来代理更新会是一种更好的方法？

**Comment by kahaani** [comment]
可以混用两种方法。[osfans/rime-tool](https://github.com/osfans/rime-tool) 就是这样做的。

对于已经托管在 GitHub 上的方案，用`git submodule update`还是要比联系作者方便。

**Comment by laubonghaudoi** [comment]
> 
> 
> 可以混用两种方法。[osfans/rime-tool](https://github.com/osfans/rime-tool) 就是这样做的。
> 
> 对于已经托管在 GitHub 上的方案，用`git submodule update`还是要比联系作者方便。

我已经将本项目拆分为两部分，一部分位于`data/`路径下，专门用于存放submodule，另一部分为`download/`路径，即为原来的文件，用于方便用户直接下载使用。我会定期检查`data/`内的各个submodule是否有更新，并将其覆盖到`download/`中，不知阁下认为这种模式如何。
