### ISSUE TITLE
官網標點捉蟲

### ISSUE THREAD

**Issue by Guanchishan** [laubonghaudoi/Chinese_Rime#18]
https://laubonghaudoi.github.io/hanhngiox/blog/schema.html#%E5%AE%A2%E5%AE%B6%E8%AF%9D

> 对于以客家话为母语、想尽快学会客拼打字的朋友，可直接阅读此官方教程

教程兩字後頭漏了冒號XD

**Comment by laubonghaudoi** [comment]
感謝反饋，最近比較忙沒時間修改，能不能直接PR到這個倉庫？我接受之後就能馬上佈署生效https://github.com/laubonghaudoi/hanhngiox
另外也歡迎其他修補和改進，感謝支持

**Comment by Guanchishan** [comment]
added: https://github.com/laubonghaudoi/hanhngiox/pull/2

**Comment by laubonghaudoi** [comment]
感謝貢獻，剛剛已經合併了PR，歡迎其他修改。
