### ISSUE TITLE
分區問題

### ISSUE THREAD

**Issue by shinzoqchiuq** [laubonghaudoi/Chinese_Rime#19]
《中國語言地圖集 第一版》中，武漢話屬於西南官話，黃岡和鄂州屬於江淮官話，南寧平話屬於桂南平話。第二版同第一版。
[官话之三](http://www.guguolin.com/img.php?book=map_zgyydtj&page=22)
[官话之六](http://www.guguolin.com/img.php?book=map_zgyydtj&page=28)
[广西壮族自治区汉语方言](http://www.guguolin.com/img.php?book=map_zgyydtj&page=46)

**Comment by laubonghaudoi** [comment]
武漢黃岡鄂州話的分類，是我和原作者討論後得到的結果，要由他來解釋 @yuxifongfei 
平話歸到粵語是我的疏忽，我之後會更新（或者閣下也可以直接修正，謝謝）
