### ISSUE TITLE
请求帮忙试试部署教程在 iRime 2.3.2 上是否依然有效

### ISSUE THREAD

**Issue by kahaani** [laubonghaudoi/Chinese_Rime#2]
你好。我按[本项目教程](https://laubonghaudoi.github.io/dialects/install/ios.html)中的步骤尝试添加方案`wugniu_soutseu`，遇到了和[这里](https://github.com/jimmy54/iRime/issues/51#issuecomment-462726005)一样的问题，即部署之后打不出字来。请问你写教程时所用的版本2.3是能正常部署的吗？我想确认是不是iRime有regression。谢谢。

**Comment by laubonghaudoi** [comment]
刚才再试了一遍，你说的问题的确存在。我部署完苏州话方案之后在选择方案列表上能找到并选用苏州话一项，但打字只能出英文字母，如图示
![_20190213092105](https://user-images.githubusercontent.com/11172180/52730645-bae62b80-2f70-11e9-8a3b-d17ef4840047.png)
我在写教程的时候是一切正常的，但我的手机和写教程时的相比，除了iRime由2.3更新至2.3.2之外，系统也从iOS 12.1.2更新至12.1.4，我无法确定是什么原因导致。感谢指出此问题，因为这可能意味着到所有方案都无法使用，如有新消息希望能告知，希望iRime作者能尽快修复。如果你有其他的临时解决方案也麻烦尽快告知我，非常感谢。

**Comment by kahaani** [comment]
@laubonghaudoi 谢谢帮忙验证 :thumbsup:

**Comment by laubonghaudoi** [comment]
@Kahaani 不客气。本issue继续保持开启状态，还要麻烦你在找到解决办法或等iRime问题修复后在这里留个言，再关闭本issue。

**Comment by jimmy54** [comment]
使用新的3.0.0版本

**Comment by laubonghaudoi** [comment]
@jimmy54 我在更新了之後反而完全不能用了，就連之前的直接從列表裏點擊下載粵拼都不行，因爲列表裏只有幾個預置方案，雲方案都沒有顯示。而且反覆出現部署失敗的提示，請問是什麼原因？
