### ISSUE TITLE
徵求志願人士幫忙維護 HanhNgiox.net

### ISSUE THREAD

**Issue by laubonghaudoi** [laubonghaudoi/Chinese_Rime#20]
本人最近工作繁忙，無暇繼續維護開發 HanhNgiox.net，目前有一個開發到一半尚未完工的[新版HanhNgiox.net網站](https://sinolect.netlify.com/)，需要請人幫手繼續開發。歡迎有意向者聯繫我，不勝感激。

**Comment by laubonghaudoi** [comment]
網站已停運

**Comment by 0xis-cn** [comment]
在本倉庫看到該站鏈接，請問還會接手麼？

**Comment by laubonghaudoi** [comment]
@0xis-cn 已經關閉，因為缺少訪問量

**Comment by laubonghaudoi** [comment]
@0xis-cn 項目網站重啓 https://laubonghaudoi.github.io/Chinese_Rime/
