### ISSUE TITLE
收录请求：晋语汾阳话输入方案

### ISSUE THREAD

**Issue by Hynuza** [laubonghaudoi/Chinese_Rime#23]
晋语汾阳话输入方案制作完成，相关文件：https://github.com/Hynuza/fengyo

**Comment by shinzoqchiuq** [comment]
非常感谢。已经收录。
https://github.com/laubonghaudoi/Chinese_Rime/commit/221caa01ef366b0babe2e5b850382f51f4ca17cc

**Comment by laubonghaudoi** [comment]
@Hynuza 非常感謝！請問能否在項目 READEM 也加入拼音方案表？

**Comment by Hynuza** [comment]
> @Hynuza 非常感謝！請問能否在項目 READEM 也加入拼音方案表？

感谢提示。已增加：
https://github.com/Hynuza/fengyo
