### ISSUE TITLE
湘語投稿

### ISSUE THREAD

**Issue by AlfredLouis00** [laubonghaudoi/Chinese_Rime#24]
我目前在製作和完善湘語婁邵片邵東地區的方言輸入方案，已經初步可用；github鏈接如下
https://github.com/AlfredLouis00/rime-inputting-method-of-Sautungva

**Comment by laubonghaudoi** [comment]
謝謝！請問有沒有一個拼音方案表？類似於[這樣的](https://kahaani.github.io/gatian/appendix1/dieziu.html)包括所有聲母韻母聲調表，最好有對應的語音描述。我看README 裏好像已經有列出所有拼音，應該做成表格就可以了。

還有就是，repo名可以精簡一下，例如改成 rime-sautungva 這樣，方便以後維護

**Comment by shinzoqchiuq** [comment]
感謝，上上週已經收錄了。
https://github.com/laubonghaudoi/Chinese_Rime/commit/d1ae6a8fdd192201848363b4f0659253bc605bb3

**Comment by AlfredLouis00** [comment]
> 

我找時間做一下對應表以及修改repo名

**Comment by AlfredLouis00** [comment]
![屏幕截图 2022-09-04 215158](https://user-images.githubusercontent.com/98323252/188317125-c401994a-f920-4f8a-8cee-b5d47b109355.png)
這是聲母的，因為我做了兩個方案，紅是`邵東話`輸入方案，藍是`邵東話拼音`輸入方案的傳寫，方括號里是國際音標，到時韻母也是紅藍標註

**Comment by laubonghaudoi** [comment]
> 感謝，上上週已經收錄了。 [d1ae6a8](https://github.com/laubonghaudoi/Chinese_Rime/commit/d1ae6a8fdd192201848363b4f0659253bc605bb3)

謝謝！現在上游repo已經改了名，readme裏的名稱能麻煩你也改一下嗎？

**Comment by shinzoqchiuq** [comment]
> > 感謝，上上週已經收錄了。 [d1ae6a8](https://github.com/laubonghaudoi/Chinese_Rime/commit/d1ae6a8fdd192201848363b4f0659253bc605bb3)
> 
> 謝謝！現在上游repo已經改了名，readme裏的名稱能麻煩你也改一下嗎？

改好了。https://github.com/laubonghaudoi/Chinese_Rime/commit/4798a42b6fbce5c85ddcd62244337a5f7f1b9c62

**Comment by laubonghaudoi** [comment]
謝謝！那收錄完成了，如果還有問題可以再開 issue 解決
