### ISSUE TITLE
上古漢語擬音輸入方案傳遞

### ISSUE THREAD

**Issue by Hulenkius** [laubonghaudoi/Chinese_Rime#25]
近製上古漢語擬音輸入方案六式，收錄以下諸家擬音：

- 白一平 1992 版擬音
- 白一平-沙加爾擬音
- 許思萊擬音（上古、東漢）
- 鄭張尚芳擬音
- msoeg 擬音

倉庫在 [Hulenkius/RIME_OC_collections](https://github.com/Hulenkius/RIME_OC_collections)

**Comment by shinzoqchiuq** [comment]
非常感謝！

是否可以把輸入方案放到頂層目錄呢，或者也可以把各個方案分別放到不同的倉庫。現在這樣還不能算是一個配方，也不方便用戶使用 `plum` 安裝。

我現在把輸入方案放到 `download/上古漢語` 下了。由於不是配方，所以沒有添加到 `source` 文件夾內。

https://github.com/laubonghaudoi/Chinese_Rime/commit/0aec740d8c9bc98ab724afbe76c17e8f97a77d29

**Comment by Hulenkius** [comment]
好的，已對目錄結構進行匹配。

此外：`OC_zhengzhangQH` 方案不成熟，已刪除，希望貴項目***不收錄*** 。對應的 README.md 已更新。

**Comment by shinzoqchiuq** [comment]
感謝，已添加到 `sources` 文件夾下，`OC_zhengzhangQH` 方案也已刪去。

https://github.com/laubonghaudoi/Chinese_Rime/commit/f4b6ccf808d93689afd7f00901d042e8cb5f597a
