### ISSUE TITLE
泰如拼音隨便用

### ISSUE THREAD

**Issue by osfans** [laubonghaudoi/Chinese_Rime#3]
網站是我維護的。字典作者有開放漢字的讀音，隨便用。
最新的碼表在這裏：
http://taerv.nguyoeh.com/ime/

**Comment by laubonghaudoi** [comment]
@osfans 非常感谢！请问能否把这个方案码表放上github将其配方化呢？因为如果仅仅只有个yaml文件的话需要手动部署很麻烦，配方化后输入法能直接从仓库抓取方案，方便推广使用。

另外，这个方案是否由吴语协会版吴拼修改而成？还是吴语学堂版方案修改而成？我见到里面有分简繁和有无声调版，如果要进行统一推广的话，最好只选其中一个例如繁体有声调版进行统一推广。

**Comment by osfans** [comment]
已提交。

**Comment by osfans** [comment]
前期是吳拼，後來聲母還是改成普通話拼音了。

**Comment by laubonghaudoi** [comment]
抱歉github一直沒有收到消息提醒，現在纔看到。請問配方地址是哪裏呢？

**Comment by laubonghaudoi** [comment]
@osfans 剛纔的[提交](https://github.com/laubonghaudoi/Chinese_Rime/commit/c9dc2f890a2986c922eada6200c81517c6fd9256)加入了泰如拼音，因爲找不到配方所以暫時放到了unmaintained目錄下。如果閣下覺得沒有問題的話這個issue就可以關閉了。如果能夠另開一個倉庫專用作泰如拼音的倉庫就最好了，希望到時告知我配方地址以及時收錄。

**Comment by osfans** [comment]
你說的配方是什麼？schema.yaml？

**Comment by laubonghaudoi** [comment]
@osfans 配方就是指新开一个repo，然后把方案的`.schema.yaml`和`.dict.yaml`文件放在最顶层目录，可参考这个[苏州话方案配方](https://github.com/NGLI/rime-wugniu_soutseu)，然后在README上写上方案简介。方案配方化后，就可以通过配方的名称，例如这个苏州话配方`NGLI/rime-wugniu_soutseu`，让输入法程序自动抓取配方，实现一键下载部署方案的功能。如此非常方便，无需手动复制粘贴方案文件再重新部署。

阁下可以先打开【小狼毫】方案選單設定，然后点击“獲取更多輸入方案”，然后会出现一个命令行界面，这时输入`NGLI/rime-wugniu_soutseu`再回车，就会发现命令行在自动抓取苏州话方案。抓取成功后再关闭命令行，就可以再在方案选单列表上看到“吳語（蘇州）”的选项。如此为一键抓取部署方案的步骤。

**Comment by osfans** [comment]
噢，所以要放到顶层目录。

**Comment by laubonghaudoi** [comment]
@osfans 是的，希望配方化后能尽快告知我地址。另外想请问一下，同文输入法什么时候能加入像小狼毫一样利用plum来自动抓取方案的功能？（或者说使用iRime一样的中心化管理方式）

**Comment by osfans** [comment]
提交了
https://github.com/osfans/rime-taerv
