### ISSUE TITLE
閩語已經八分

### ISSUE THREAD

**Issue by ZauberViolino** [laubonghaudoi/Chinese_Rime#31]
https://iso639-3.sil.org/code/zho ，海南、雷州、邵將已經獨立，似乎並無配方，只需在「暫缺」中加入即可。

**Comment by laubonghaudoi** [comment]
![image](https://github.com/user-attachments/assets/57ebbe15-38b4-4278-97db-b050c0ed3ab7)
我知道曾經有個提案，潮州話獨立為`tws`，但似乎已經找不到頁面。歡迎提交 PR 修改

**Comment by laubonghaudoi** [comment]
哦找到了，原來潮州話已經被否決？https://iso639-3.sil.org/request/2021-045 所以原來雷州話不算閩南話？

**Comment by ZauberViolino** [comment]
#32.

> 原來雷州話不算閩南話？

雷州片在2012地圖集被劃出閩南片（區），1987地圖集還在閩南區。

> 潮州話已經被否決？

兩版《地圖集》，潮汕（小）片一直在閩南區（片）下。2021-045的最終決定就是根據《地圖集》作出的。

**Comment by laubonghaudoi** [comment]
感謝PR，不過我覺得莫名其妙，如果連黎話都可以拆成雷州話和瓊州話，潮州話更應該分開。
