### ISSUE TITLE
沒有blg_etai的submodule

### ISSUE THREAD

**Issue by szc126** [laubonghaudoi/Chinese_Rime#4]
README裏有記錄着blg_etai，但我卻找不到blg_etai的submodule。

**Comment by laubonghaudoi** [comment]
感谢指正，已经把链接[补全](https://github.com/laubonghaudoi/Chinese_Rime/commit/4d307c26028b357ca6a52b415098ac273ea38894)，闽南语输入法的仓库在此[LimTo/etaiBLG
](https://github.com/LimTo/etaiBLG)
